vendor/nvidia/jetson/proprietary/framework/com.google.widevine.software.drm.jar:framework/com.google.widevine.software.drm.jar \
vendor/nvidia/jetson/proprietary/app/LeanbackIme/LeanbackIme.apk:app/LeanbackIme/LeanbackIme.apk \
vendor/nvidia/jetson/proprietary/etc/nvram_43241.txt:etc/nvram_43241.txt \
vendor/nvidia/jetson/proprietary/etc/bluetooth/bdaddr:etc/bluetooth/bdaddr \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_aud_ucode.bin:etc/firmware/nvavp_aud_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_vid_ucode.bin:etc/firmware/nvavp_vid_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_os_8ff00000.bin:etc/firmware/nvavp_os_8ff00000.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/bcm43241.hcd:etc/firmware/bcm43241.hcd \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_os_eff00000.bin:etc/firmware/nvavp_os_eff00000.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_os_0ff00000.bin:etc/firmware/nvavp_os_0ff00000.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_os_f7e00000.bin:etc/firmware/nvavp_os_f7e00000.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/iwlwifi-7260-8.ucode:etc/firmware/iwlwifi-7260-8.ucode \
vendor/nvidia/jetson/proprietary/etc/firmware/brcm_p2p.conf:etc/firmware/brcm_p2p.conf \
vendor/nvidia/jetson/proprietary/etc/firmware/fw-0a5c_21e8.hcd:etc/firmware/fw-0a5c_21e8.hcd \
vendor/nvidia/jetson/proprietary/etc/firmware/brcm_wpa.conf:etc/firmware/brcm_wpa.conf \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:etc/firmware/nvavp_vid_ucode_alt.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/tegra12x/vic03_ucode.bin:etc/firmware/tegra12x/vic03_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/tegra12x/nvhost_tsec.fw:etc/firmware/tegra12x/nvhost_tsec.fw \
vendor/nvidia/jetson/proprietary/etc/firmware/tegra12x/nvhost_msenc031.fw:etc/firmware/tegra12x/nvhost_msenc031.fw \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_mp3dec_ucode.bin:etc/firmware/nvavp_mp3dec_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/iwlwifi-7260-7.ucode:etc/firmware/iwlwifi-7260-7.ucode \
vendor/nvidia/jetson/proprietary/etc/firmware/nvavp_aacdec_ucode.bin:etc/firmware/nvavp_aacdec_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/gk20a/NETB_img.bin:etc/firmware/gk20a/NETB_img.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/gk20a/gpccs.bin:etc/firmware/gk20a/gpccs.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/gk20a/fecs.bin:etc/firmware/gk20a/fecs.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/gk20a/gpmu_ucode.bin:etc/firmware/gk20a/gpmu_ucode.bin \
vendor/nvidia/jetson/proprietary/etc/firmware/tegra_xusb_firmware:etc/firmware/tegra_xusb_firmware \
vendor/nvidia/jetson/proprietary/etc/firmware/intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq:etc/firmware/intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq \
vendor/nvidia/jetson/proprietary/etc/firmware/iwlwifi-7260-9.ucode:etc/firmware/iwlwifi-7260-9.ucode \
vendor/nvidia/jetson/proprietary/etc/permissions/com.google.widevine.software.drm.xml:etc/permissions/com.google.widevine.software.drm.xml \
vendor/nvidia/jetson/proprietary/etc/hdcpsrm/hdcp1x.srm:etc/hdcpsrm/hdcp1x.srm \
vendor/nvidia/jetson/proprietary/etc/hdcpsrm/hdcp2xtest.srm:etc/hdcpsrm/hdcp2xtest.srm \
vendor/nvidia/jetson/proprietary/etc/hdcpsrm/hdcp2x.srm:etc/hdcpsrm/hdcp2x.srm \
vendor/nvidia/jetson/proprietary/etc/ussrd.conf:etc/ussrd.conf \
vendor/nvidia/jetson/proprietary/etc/enctune.conf:etc/enctune.conf \
vendor/nvidia/jetson/proprietary/lib/libsensors.ltr558als.so:lib/libsensors.ltr558als.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.nvs_input.so:lib/libsensors.nvs_input.so \
vendor/nvidia/jetson/proprietary/lib/hw/sensors.tegra.so:lib/hw/sensors.tegra.so \
vendor/nvidia/jetson/proprietary/lib/hw/gps.brcm.so:lib/hw/gps.brcm.so \
vendor/nvidia/jetson/proprietary/lib/libtbb.so:lib/libtbb.so \
vendor/nvidia/jetson/proprietary/lib/libinvensense_hal.so:lib/libinvensense_hal.so \
vendor/nvidia/jetson/proprietary/lib/nvcms/device.cfg:lib/nvcms/device.cfg \
vendor/nvidia/jetson/proprietary/lib/libopencv24_tegra.so:lib/libopencv24_tegra.so \
vendor/nvidia/jetson/proprietary/lib/libmllite.so:lib/libmllite.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.iio.lights.so:lib/libsensors.iio.lights.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.max44005.so:lib/libsensors.max44005.so \
vendor/nvidia/jetson/proprietary/lib/libmplmpu.so:lib/libmplmpu.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.mpl.so:lib/libsensors.mpl.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.bmpx80.so:lib/libsensors.bmpx80.so \
vendor/nvidia/jetson/proprietary/lib/libsensors.base.so:lib/libsensors.base.so \
vendor/nvidia/jetson/proprietary/lib/libremotecontrolservice.so:lib/libremotecontrolservice.so \
vendor/nvidia/jetson/proprietary/lib/modules/raw_ip_net.ko:lib/modules/raw_ip_net.ko \
vendor/nvidia/jetson/proprietary/lib/modules/gspca_main.ko:lib/modules/gspca_main.ko \
vendor/nvidia/jetson/proprietary/lib/modules/tcrypt.ko:lib/modules/tcrypt.ko \
vendor/nvidia/jetson/proprietary/lib/modules/rtl8723ae.ko:lib/modules/rtl8723ae.ko \
vendor/nvidia/jetson/proprietary/vendor/framework/com.nvidia.graphics.jar:vendor/framework/com.nvidia.graphics.jar \
vendor/nvidia/jetson/proprietary/vendor/lib/libaudioavp.so:vendor/lib/libaudioavp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libtsec_wrapper.so:vendor/lib/libtsec_wrapper.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_parser.so:vendor/lib/libnvmm_parser.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/audio.primary.tegra.so:vendor/lib/hw/audio.primary.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/camera.tegra.so:vendor/lib/hw/camera.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/memtrack.tegra.so:vendor/lib/hw/memtrack.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/hwcomposer.tegra.so:vendor/lib/hw/hwcomposer.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/keystore.tegra.so:vendor/lib/hw/keystore.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/ts.default.so:vendor/lib/hw/ts.default.so \
vendor/nvidia/jetson/proprietary/vendor/lib/hw/gralloc.tegra.so:vendor/lib/hw/gralloc.tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_07_00_b0.so:vendor/lib/para_10_07_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_09_01_c0.so:vendor/lib/para_10_09_01_c0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcpl.so:vendor/lib/libnvcpl.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvstitching.so:vendor/lib/libnvstitching.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvomxilclient.so:vendor/lib/libnvomxilclient.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcapaudioservice.so:vendor/lib/libnvcapaudioservice.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_gpucompute.so:vendor/lib/libgov_gpucompute.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvhdcp.so:vendor/lib/libnvhdcp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_09_00_c0.so:vendor/lib/para_10_09_00_c0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_combinator.so:vendor/lib/libgov_combinator.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_02_00_b0.so:vendor/lib/para_10_02_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_generic.so:vendor/lib/libgov_generic.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvapputil.so:vendor/lib/libnvapputil.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_05_00_c0.so:vendor/lib/para_10_05_00_c0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_0b_00_a0.so:vendor/lib/para_10_0b_00_a0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_03_00_b0.so:vendor/lib/para_10_03_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvparser.so:vendor/lib/libnvparser.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcms.so:vendor/lib/libnvcms.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_graphics.so:vendor/lib/libgov_graphics.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_ui.so:vendor/lib/libgov_ui.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvavp.so:vendor/lib/libnvavp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvisp.so:vendor/lib/libnvisp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_06_00_b0.so:vendor/lib/para_10_06_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_04_00_c0.so:vendor/lib/para_10_04_00_c0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcamerahdr_v3.so:vendor/lib/libnvcamerahdr_v3.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvisp_v3.so:vendor/lib/libnvisp_v3.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libfcamdng.so:vendor/lib/libfcamdng.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcam_imageencoder.so:vendor/lib/libnvcam_imageencoder.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libstagefrighthw.so:vendor/lib/libstagefrighthw.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_camera_v3.so:vendor/lib/libnvmm_camera_v3.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvwsi.so:vendor/lib/libnvwsi.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libwvm.so:vendor/lib/libwvm.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libussrd.so:vendor/lib/libussrd.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvtvmr.so:vendor/lib/libnvtvmr.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvsm.so:vendor/lib/libnvsm.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvblit.so:vendor/lib/libnvblit.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_03_00_20.so:vendor/lib/para_10_03_00_20.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_force.so:vendor/lib/libgov_force.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libcuda.so:vendor/lib/libcuda.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libglcore.so:vendor/lib/libglcore.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmmlite_utils.so:vendor/lib/libnvmmlite_utils.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvddk_vic.so:vendor/lib/libnvddk_vic.so \
vendor/nvidia/jetson/proprietary/vendor/lib/liboemcrypto.so:vendor/lib/liboemcrypto.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm.so:vendor/lib/libnvmm.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_02_00_a0.so:vendor/lib/para_10_02_00_a0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvfusebypass.so:vendor/lib/libnvfusebypass.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvomx.so:vendor/lib/libnvomx.so \
vendor/nvidia/jetson/proprietary/vendor/lib/egl/libGLESv2_tegra.so:vendor/lib/egl/libGLESv2_tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:vendor/lib/egl/libGLESv1_CM_tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/egl/libEGL_tegra.so:vendor/lib/egl/libEGL_tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvtnr.so:vendor/lib/libnvtnr.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libtsechdcp.so:vendor/lib/libtsechdcp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_02_00_20.so:vendor/lib/para_10_02_00_20.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_08_00_20.so:vendor/lib/para_10_08_00_20.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libwvdrm_L1.so:vendor/lib/libwvdrm_L1.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmmlite_image.so:vendor/lib/libnvmmlite_image.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libaudiopolicymanager.so:vendor/lib/libaudiopolicymanager.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_il.so:vendor/lib/libgov_il.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvglsi.so:vendor/lib/libnvglsi.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvodm_imager.so:vendor/lib/libnvodm_imager.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_camera.so:vendor/lib/libnvmm_camera.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvvicsi.so:vendor/lib/libnvvicsi.so \
vendor/nvidia/jetson/proprietary/vendor/lib/librm_ts_service.so:vendor/lib/librm_ts_service.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvgr.so:vendor/lib/libnvgr.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvaudioservice.so:vendor/lib/libnvaudioservice.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvaudiofx.so:vendor/lib/libnvaudiofx.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_04_00_b0.so:vendor/lib/para_10_04_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_08_00_a0.so:vendor/lib/para_10_08_00_a0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/drm/libdrmwvmplugin.so:vendor/lib/drm/libdrmwvmplugin.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libclcore_nvidia.bc:vendor/lib/libclcore_nvidia.bc \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvrm.so:vendor/lib/libnvrm.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_writer.so:vendor/lib/libnvmm_writer.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmmlite.so:vendor/lib/libnvmmlite.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcapclk.so:vendor/lib/libnvcapclk.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_tbc.so:vendor/lib/libgov_tbc.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_spincircle.so:vendor/lib/libgov_spincircle.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libdrmdecrypt.so:vendor/lib/libdrmdecrypt.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmmlite_audio.so:vendor/lib/libnvmmlite_audio.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_camera.so:vendor/lib/libgov_camera.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvcamerahdr.so:vendor/lib/libnvcamerahdr.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libstagefright_hdcp.so:vendor/lib/libstagefright_hdcp.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvddk_2d_v2.so:vendor/lib/libnvddk_2d_v2.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libscf.so:vendor/lib/libscf.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvoice.so:vendor/lib/libnvoice.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvwinsys.so:vendor/lib/libnvwinsys.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvhwc_service.so:vendor/lib/libnvhwc_service.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_0a_00_b0.so:vendor/lib/para_10_0a_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_08_00_b0.so:vendor/lib/para_10_08_00_b0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_03_00_a0.so:vendor/lib/para_10_03_00_a0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libgov_boot.so:vendor/lib/libgov_boot.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvos.so:vendor/lib/libnvos.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libtlk_secure_hdcp_up.so:vendor/lib/libtlk_secure_hdcp_up.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvrm_graphics.so:vendor/lib/libnvrm_graphics.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvrmapi_tegra.so:vendor/lib/libnvrmapi_tegra.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvomxadaptor.so:vendor/lib/libnvomxadaptor.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_contentpipe.so:vendor/lib/libnvmm_contentpipe.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_audio.so:vendor/lib/libnvmm_audio.so \
vendor/nvidia/jetson/proprietary/vendor/lib/para_10_09_02_c0.so:vendor/lib/para_10_09_02_c0.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:vendor/lib/libWVStreamControlAPI_L1.so \
vendor/nvidia/jetson/proprietary/vendor/lib/librm31080.so:vendor/lib/librm31080.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvvicsi_v3.so:vendor/lib/libnvvicsi_v3.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmmlite_video.so:vendor/lib/libnvmmlite_video.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libphs.so:vendor/lib/libphs.so \
vendor/nvidia/jetson/proprietary/vendor/lib/libnvmm_utils.so:vendor/lib/libnvmm_utils.so \
vendor/nvidia/jetson/proprietary/vendor/bin/raydium_selftest:vendor/bin/raydium_selftest \
vendor/nvidia/jetson/proprietary/vendor/bin/ussrd:vendor/bin/ussrd \
vendor/nvidia/jetson/proprietary/vendor/bin/tsechdcp_test:vendor/bin/tsechdcp_test \
vendor/nvidia/jetson/proprietary/vendor/bin/pbc:vendor/bin/pbc \
vendor/nvidia/jetson/proprietary/vendor/bin/nv_hciattach:vendor/bin/nv_hciattach \
vendor/nvidia/jetson/proprietary/vendor/bin/FinalTestThresholdManage.ini:vendor/bin/FinalTestThresholdManage.ini \
vendor/nvidia/jetson/proprietary/vendor/bin/rm_test:vendor/bin/rm_test \
vendor/nvidia/jetson/proprietary/vendor/bin/tegrastats:vendor/bin/tegrastats \
vendor/nvidia/jetson/proprietary/vendor/bin/rm_panel_setting.ini:vendor/bin/rm_panel_setting.ini \
vendor/nvidia/jetson/proprietary/vendor/bin/tlk_daemon:vendor/bin/tlk_daemon \
vendor/nvidia/jetson/proprietary/vendor/bin/rm_ts_server:vendor/bin/rm_ts_server \
vendor/nvidia/jetson/proprietary/vendor/bin/hdcp_test:vendor/bin/hdcp_test \
vendor/nvidia/jetson/proprietary/vendor/bin/btmacwriter:vendor/bin/btmacwriter \
vendor/nvidia/jetson/proprietary/vendor/firmware/rtlwifi/rtl8723fw_B.bin:vendor/firmware/rtlwifi/rtl8723fw_B.bin \
vendor/nvidia/jetson/proprietary/vendor/firmware/bcm43241/fw_bcmdhd.bin:vendor/firmware/bcm43241/fw_bcmdhd.bin \
vendor/nvidia/jetson/proprietary/bin/set_hwui_params.sh:bin/set_hwui_params.sh \
vendor/nvidia/jetson/proprietary/bin/gps_select.sh:bin/gps_select.sh \
vendor/nvidia/jetson/proprietary/bin/glgps_nvidiaTegra2android:bin/glgps_nvidiaTegra2android \
vendor/nvidia/jetson/proprietary/bin/wifi_loader.sh:bin/wifi_loader.sh \
vendor/nvidia/jetson/proprietary/bin/ussr_setup.sh:bin/ussr_setup.sh \
vendor/nvidia/jetson/proprietary/priv-app/RemoteControlService/RemoteControlService.apk:priv-app/RemoteControlService/RemoteControlService.apk \
vendor/nvidia/jetson/proprietary/priv-app/TV/TV.apk:priv-app/TV/TV.apk \
vendor/nvidia/jetson/proprietary/priv-app/AtvRemoteService/lib/arm/libatv_uinputbridge.so:priv-app/AtvRemoteService/lib/arm/libatv_uinputbridge.so \
vendor/nvidia/jetson/proprietary/priv-app/AtvRemoteService/AtvRemoteService.apk:priv-app/AtvRemoteService/AtvRemoteService.apk \
vendor/nvidia/jetson/proprietary/priv-app/Android.mk:priv-app/Android.mk \
vendor/nvidia/jetson/proprietary/priv-app/GamepadPairingService/GamepadPairingService.apk:priv-app/GamepadPairingService/GamepadPairingService.apk \
vendor/nvidia/jetson/proprietary/priv-app/NvSDManagerService/NvSDManagerService.apk:priv-app/NvSDManagerService/NvSDManagerService.apk \
vendor/nvidia/jetson/proprietary/priv-app/GlobalKeyInterceptor/GlobalKeyInterceptor.apk:priv-app/GlobalKeyInterceptor/GlobalKeyInterceptor.apk \
vendor/nvidia/jetson/proprietary/priv-app/NvCustomize/NvCustomize.apk:priv-app/NvCustomize/NvCustomize.apk \
vendor/nvidia/jetson/proprietary/priv-app/LeanbackLauncher/LeanbackLauncher.apk:priv-app/LeanbackLauncher/LeanbackLauncher.apk \
